Repository ford-of-the-strings/acebook-android, pull requests merged in 2019-06, with the labels that each got.

#1 Travis set up
  .travis.yml
  app/build.gradle
  app/src/androidTest/java/com/fots/acebook/ExampleInstrumentedTest.java
Labels: LGTM (Piers)

#2 added constraints to multiline posts
  app/src/main/java/com/fots/acebook/MainActivity.java
  app/src/main/res/layout/content_list_post_view.xml
  app/src/main/res/layout/content_main.xml
Labels: LGTM (Peter)

#4 reversed the order of posts so most recent at top
  app/src/main/java/com/fots/acebook/ListPostsActivity.java
  app/src/main/java/com/fots/acebook/MainActivity.java
  app/src/main/java/com/fots/acebook/PostAdapter.java
Labels: LGTM (Egle)

#5 Updated titles to acebook rather than my_app and changed primary colo…
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: LGTM (Peter)

#7 Post dates
  app/src/main/java/com/fots/acebook/MainActivity.java
  app/src/main/java/com/fots/acebook/PostAdapter.java
  app/src/main/java/com/fots/acebook/models/Post.java
  app/src/main/res/layout/content_list_post_view.xml
  app/src/main/res/layout/content_main.xml
  app/src/main/res/values/strings.xml
Labels: LGTM (Adrian)

#16 Change app icon
  app/src/main/ic_launcher-web.png
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.png
  app/src/main/res/mipmap-hdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  app/src/main/res/mipmap-mdpi/ic_launcher.png
  app/src/main/res/mipmap-mdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xhdpi/ic_launcher.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  app/src/main/res/values/ic_launcher_background.xml
Labels: LGTM (Peter)

#17 Refactoring
  app/src/main/java/com/fots/acebook/Authentication.java
  app/src/main/java/com/fots/acebook/CreatePostActivity.java
  app/src/main/java/com/fots/acebook/ListPostsActivity.java
  app/src/main/java/com/fots/acebook/MainActivity.java
  app/src/main/java/com/fots/acebook/PostAdapter.java
  app/src/main/java/com/fots/acebook/ToolbarActivity.java
  app/src/main/java/com/fots/acebook/UpdatePostActivity.java
Labels: LGTM (Egle), LGTM (Peter)
